services:
  app1:
    build: 
      context: ..
      dockerfile: docker/node/Dockerfile
    environment:
      - APP_NAME=App1
    networks:
      - backend

  app2:
    build: 
      context: ..
      dockerfile: docker/node/Dockerfile
    environment:
      - APP_NAME=App2
    networks:
      - backend

  app3:
    build: 
      context: ..
      dockerfile: docker/node/Dockerfile
    environment:
      - APP_NAME=App3
    networks:
      - backend    

  reverse-proxy:
    build: 
      context: ./nginx
    ports:
      - "8080:8080"  
    networks:
      - backend
    depends_on:
      - app1
      - app2
      - app3
networks:
  backend: {}        